export const TEXT = {
  SECTION_TITLE: "Loại phòng",
  SECTION_HINT: "Thêm loại phòng + gói giá (rate plan) + tiện ích phòng (scope ROOM).",
  ADD_ROOM: "Thêm loại phòng",
  ROOM_PREFIX: "Phòng",
  ROOM_UNNAMED: "(chưa đặt tên)",
  CODE_LABEL: "Mã phòng",
  MOVE_UP: "Lên",
  MOVE_DOWN: "Xuống",
  DELETE_ROOM: "Xóa phòng",

  BASIC_NAME: "Tên phòng *",
  BASIC_CODE: "Mã phòng *",
  BASIC_DESC: "Mô tả",
  BASIC_AREA: "Diện tích (m²)",
  BASIC_QTY: "Số lượng phòng",
  BASIC_MAX_ADULTS: "Tối đa người lớn",
  BASIC_MAX_CHILDREN: "Tối đa trẻ em",
  CODE_AUTO: "Mã tự tạo theo tên phòng (có thể sửa).",
  CODE_MANUAL: "Bạn đang sửa mã thủ công.",

  IMAGES_TITLE: "Ảnh phòng",
  IMAGES_HINT: "Thêm ảnh bằng link hoặc tải từ máy (preview).",
  PASTE_IMAGE_URL: "Dán link ảnh...",
  ADD_BY_URL: "Thêm link",
  UPLOAD_IMAGES: "Tải ảnh",
  NO_IMAGES: "Chưa có ảnh phòng.",
  SET_COVER: "Đặt làm ảnh bìa",
  COVER: "Ảnh bìa",
  DELETE_IMAGE: "Xóa ảnh",

  BEDS_TITLE: "Giường",
  ADD_BED: "Thêm giường",
  BED_COUNT: "Số lượng",
  DELETE: "Xóa",

  RATE_PLANS_TITLE: "Gói giá (Rate plans)",
  ADD_RATE_PLAN: "Thêm gói giá",
  NO_RATE_PLANS: "Chưa có gói giá.",
  RP_NAME: "Tên gói",
  RP_CODE: "Mã gói",
  RP_BOARD: "Bữa ăn",
  RP_PAYMENT: "Thanh toán",
  RP_PRICE: "Giá/đêm",
  RP_REF_PRICE: "Giá gốc/đêm",
  RP_REFUNDABLE: "Hoàn/Hủy được",
  RP_INCLUDES_TAX: "Đã gồm thuế",
  RP_INCLUDES_FEE: "Đã gồm phí DV",
  RP_LOW_AVAIL: "Hiện sắp hết",
  RP_PROMO: "Nhãn khuyến mãi",
  RP_CANCEL: "Chính sách hủy",

  AMENITIES_TITLE: "Tiện ích phòng (scope ROOM)",
  AMENITIES_HINT: "Chọn các tiện ích thuộc phòng.",

  // option labels
  BOARD_OPTIONS: {
    ROOM_ONLY: "Chỉ phòng (không ăn)",
    BREAKFAST_INCLUDED: "Có ăn sáng",
    HALF_BOARD: "Ăn 2 bữa (thường sáng + tối)",
    FULL_BOARD: "Ăn 3 bữa (sáng + trưa + tối)",
},
  PAYMENT_OPTIONS: {
    PREPAID: "Thanh toán trước",
    PAY_AT_HOTEL: "Thanh toán tại khách sạn",
  },
  BED_TYPES: {
    SINGLE: "Giường đơn",
    DOUBLE: "Giường đôi",
    QUEEN: "Queen",
    KING: "King",
    TWIN: "Twin",
  },
};