export const ErrorCodes = {
  BAD_REQUEST: "BAD_REQUEST",
  NOT_FOUND: "NOT_FOUND",
  FORBIDDEN: "FORBIDDEN",
  CONFLICT: "CONFLICT",

  STALE_VERSION: "STALE_VERSION",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  CONSTRAINT_VIOLATION: "CONSTRAINT_VIOLATION",
  DATA_INTEGRITY_VIOLATION: "DATA_INTEGRITY_VIOLATION",
  INVALID_PERSISTENCE_STATE: "INVALID_PERSISTENCE_STATE",
  INTERNAL_ERROR: "INTERNAL_ERROR",

  ACCESS_REQUEST_ALREADY_SUBMITTED: "ACCESS_REQUEST_ALREADY_SUBMITTED",
  ACCESS_ALREADY_GRANTED: "ACCESS_ALREADY_GRANTED",
  ACCESS_VIEW_ALREADY_GRANTED: "ACCESS_VIEW_ALREADY_GRANTED",
};
